name: "Continuous Integration"
on: push

jobs:
  main:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --requirement requirements.txt
          pip install pyinstaller
      - name: Build with pyinstaller
        run: |
          pyinstaller --onefile --name excel-reformat-${{ matrix.os }} main.py
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: excel-reformat
          path: dist/
